### PR TITLE
Lettuce:Extra Dependencies Remove & Shift kernel Repo

### PR DESCRIPTION
**Pull request by hpnightowl**
No Need Of Extra Dependencies also Kernel tree Change Forgot these yesterday sry :)

### CODE REVIEW

**Comment by adithya2306** [comment]
dependencies should be in omni.dependencies not omni_dependencies

**Comment by hpnightowl** [comment]
lol XD SUCH A NOOB

**Comment by hpnightowl** [comment]
convert it as one commit i have deleted that repo from my pc :(

**Comment by adithya2306** [comment]
device/qcom/common is not needed and its dtbtool clashes with the one in DT (https://github.com/ghostrider-reborn/android_device_yu_lettuce-twrp/commit/f9d67f8dbfab59d7f9d412169de56884aa6c9337), so it's better to remove it

**Comment by hpnightowl** [comment]
lol BUT NOW HOW ? an i Edit? pm me :(

**Comment by adithya2306** [comment]
> lol BUT NOW HOW ? an i Edit? pm me :(

it's your PR so you gotta do it lol

**Comment by adithya2306** [comment]
or fuck it imma squash em all in one commit "Move to LineageOS kernel"

**Comment by ghostrider-reborn** [comment]
https://github.com/ghostrider-reborn/android_device_yu_lettuce-twrp/commit/645fe60cdade41196d3bf90fcead742c237f5366

**Comment by adithya2306** [comment]
https://github.com/ghostrider-reborn/android_device_yu_lettuce-twrp/commit/645fe60cdade41196d3bf90fcead742c237f5366

**Comment by hpnightowl** [comment]
ok :)

**Comment by Yasir-siddiqui** [comment]
:V

**Pull request closed without merging**
